### ISSUE TITLE
`tensordict.__getitem__(string)` with `_TensorDict` subclasses.

### ISSUE THREAD

**Issue by vmoens** [facebookresearch/rl#126]
`TensorDict` can be indexed in two ways: 
- If a tensor, integer, etc. is provided, then the `__getitem__` method will return a `TensorDict` tensors indexed at the right location.
- If a string is given, then the relevant key will be returned. This is exactly equivalent to `tensordict.get(string)` except that no default value can be provided. 

Currently, the second behaviour is only supported by `TensorDict` (not by other `_TensorDict` subclasses, e.g. not by `LazyStackedTensorDict` etc). This should be implemented.
 
Additionally, a test should be written in `test/test_tensordict.py` in the form of 
```python
class TestTensorDicts:
    ....
    @pytest.mark.parametrize(
        "td_name",
        [
            "td",
            "stacked_td",
            "sub_td",
            "idx_td",
            "saved_td",
            "unsqueezed_td",
            "td_reset_bs",
        ],
    )
    def test_getitem_string(self, td_name):
         ....
```
such that we make sure that all tensordict subclasses are covered. The test should demonstrate that the output of `get` and `__getitem__` are equivalent when a string is provided.

**Comment by karthikrangasai** [comment]
Can I take this up ?
