### ISSUE TITLE
[BUG] deepcopy of MLP fails

### ISSUE THREAD

**Issue by nicolas-dufour** [facebookresearch/rl#357]
## Describe the bug

When sending a TDmodule to a device (tested with cpu and mps) deepcopy fails.
The following error is raised:
```
Exception has occurred: TypeError
empty() received an invalid combination of arguments - got (int, dtype=NoneType, device=bool), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of SymInts size, *, torch.memory_format memory_format, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.memory_format memory_format, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
  File "/Users/ndufour/Documents/pytorch/rl/examples/dreamer/deepcopy debug", line 32, in <module>
    td_copy = deepcopy(td_module)
```

## To Reproduce
Here is a snippet to reproduce:

```
from copy import deepcopy
import torch
import torch.nn as nn
from torchrl.modules import TensorDictModule, MLP
mps = torch.device("mps")
cpu = torch.device("cpu")

### No bugs found in this file ###
linear = nn.Linear(10, 10).to(cpu)

td_module = TensorDictModule(
    nn.Sequential(linear),
    in_keys=["x"],
    out_keys=["y"],
).to(cpu)

lin_copy = deepcopy(linear)
td_copy = deepcopy(td_module)



### Bug found in this file ###

td_module = TensorDictModule(
    MLP(out_features=1, depth=3, num_cells=400, activation_class=nn.ELU),
    in_keys=["x"],
    out_keys=["y"],
).to(cpu)



lin_copy = deepcopy(linear)
```

## Expected behavior

Expected behaviour is that deepcopy(MLP) should not prevent doing deepcopy.

## System info

Describe the characteristic of your environment:
 * Mac OS (M1 Chip)
 * 3.9.12
 * Pytorch nightly 1.13
## Reason and Possible fixes

If you know or suspect the reason for this bug, paste the code lines and suggest modifications.

## Checklist

- [ ] I have checked that there is no similar issue in the repo (**required**)
- [ ] I have read the [documentation](https://github.com/facebookresearch/rl/tree/main/docs/) (**required**)
- [ ] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by nicolas-dufour** [comment]
Actually looking deeper into it,
```
linear = deepcopy(MLP(out_features=1, depth=3, num_cells=400, activation_class=nn.ELU)) 
```

also triggers the bug so. This isn't linked to tdmodule or the device

**Comment by vmoens** [comment]
Yes it's a known issue of lazy modules (see [here](https://github.com/pytorch/pytorch/issues/65051))
Closing as this is unrealted to torchrl.
