### ISSUE TITLE
[Feature Request] Integrate MLFlow in the loggers backends

### ISSUE THREAD

**Issue by vmoens** [facebookresearch/rl#395]
## Motivation

MLFlow would be a nice-to-have in our loggers.

## Solution

The essential features of loggers are (as of now) add_scalar and add_video.
I'm not sure if MLFlow supports videos, but if not I guess that storing it as an artifact would work? 

Note:
The split between runs and experiment is a nice to have. I suspect that integrating this with hydra won't be easy with our current config API, which is quite flat and assumed that all loggers have the same params. I suspect that this will be refactored soon, but as of now we can assume that all loggers have an experiment and run attribute.

## Tests
Tests should be implemented for the logger, with specific tests for each logging capability. See [test/test_loggers.py](https://github.com/facebookresearch/rl/blob/main/test/test_loggers.py) for context.

To test this feature, one should be able to run
```bash
python ppo.py logger=mlflow
```

**Comment by rayanht** [comment]
Would like to claim this issue, thanks!
