### ISSUE TITLE
[BUG] SAC example is broken

### ISSUE THREAD

**Issue by idanshen** [facebookresearch/rl#452]
Hi,

I cloned the repo and tried to run the SAC example without any changes to the code. After some time it just crashes:

![image](https://user-images.githubusercontent.com/49375140/190418011-8dcb7d4f-e1e6-47af-aaba-54d3b3a03f39.png)

To Reproduce
Clone the repo and run: `python sac/sac.py env_name="HalfCheetah-v4" env_task="" env_library="gym"`

**Comment by vmoens** [comment]
Thanks for flagging this let me have a look

**Comment by vmoens** [comment]
can you try checking out `fix_device_safe` and see if the problem persists?

**Comment by idanshen** [comment]
It seems to be fixed, thank you!
