### ISSUE TITLE
[Feature Request] Removing `TensorDict.device_safe()` in favour of `TensorDict.device`

### ISSUE THREAD

**Issue by vmoens** [facebookresearch/rl#455]
## Motivation

TensorDict device can now be None even when populated in a great move from @tcbegley
The current TensorDict's API will return an error in one calls `td.device` when None is set. To get this device, one should call `td.safe_device()`.

Pros:
- Users are notified that they're playing with fire
- consistent with torch in that `device` is always a `torch.device` if it exists.
- `tensor.to(tensordict.device)` won't work if the device is not set 
    -> but if the goal is to put the tensor in the tensordict, then `tensordict[key] = tensor` will already do the casting if needed

Cons:
- Inconsistent with torch
    - no code re-usability (a call to `tensor.device` must be replaced by `td.device_safe()`
    - requires some kind of learning from the users
- Pollutes the code with a lot of `if hasattr(obj, "device_safe")` and such
- In many cases a call to `tensordict.device != torch.device(smth)` is actually legit: if the device is not set, we can expect that things may break. Most of the time this will be followed by `tensordict.to(smth)` which will be an (almost) no-op if all tensors are already on device.

## Solution

Removing `device_safe` and replacing it by `device`.

**Comment by ordinskiy** [comment]
Hello @vmoens,

In most cases replacing `device_safe()` with `device` doesn't change the behaviour, but there is one case that looks suspicious https://github.com/facebookresearch/rl/blob/3d76553f0176e7ae7d3cc3b6c1e0dab4b1dda509/torchrl/data/tensordict/tensordict.py#L3860 
In `SavedTensorDict` class, when `self._device == None`, property returns `device` of the first tensor. Meanwhile `device_safe()` would return `self._device` (`None` in this case). Is this change of external looks acceptable to you?

**Comment by tcbegley** [comment]
@ordinskiy I was looking at this last week and I agree that in the case you highlighted it doesn't make to fallback to device of first tensor since #413 was merged. I think in that case the entire function could be replaced with `return self._device`. Neither the fallback logic nor the exception for `None` are relevant anymore.

**Comment by vmoens** [comment]
I agree with @tcbegley 

In theory SavedTensorDict should inherit the device of the saved TensorDict.
In other words, it should be None if the tensordict has device None.

The block where the device is gathered from the meta-tensor should be removed.
