### ISSUE TITLE
[Feature Request] Replay buffer support for storing and sampling whole trajectories

### ISSUE THREAD

**Issue by idanshen** [facebookresearch/rl#466]
## Motivation

I was trying to work with recurrent models (for example implementing https://arxiv.org/pdf/2110.05038.pdf) and got a problem trying to store and sample whole trajectories in the replay buffer instead of tuples. When training on-policy algorithm (without replay buffer) it is possible to do so using BatchSubSampler but I couldn't find a proper way to do it with off-policy algorithms.

## Solution

The main obstacle is the following lines in the ReplayBufferTrainer class:
![image](https://user-images.githubusercontent.com/49375140/190733842-5f545dd2-c233-4467-963f-3d921def3ba0.png)
It flattens the batch of trajectories into a batch of tuples. Maybe add a flag that controls this behavior?

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)

**Comment by vmoens** [comment]
Good point this helper class could have a flag to store trajectories.
Feel free to make a PR for this. 

Otherwise I'll take care of it on Tuesday when I'm back to work!

**Comment by vmoens** [comment]
@idanshen you can check #476, still WIP but it should make you happy 😊
