### ISSUE TITLE
[Feature Request] TorchRL vs Salina

### ISSUE THREAD

**Issue by joaogui1** [facebookresearch/rl#69]
Can you add a readme comparing this to [Salina](https://github.com/facebookresearch/salina)? Especially given that both are RL libraries in Torch from FAIR

**Comment by vmoens** [comment]
Sure! 
Salina is as far as I can tell not strictly RL oriented, though it's currently the main use case. It can be used for any sequential decision making or even sequential task. Salina is quite opinionated (in a good way!), it's more like a framework to model some tasks (eg there are agents and workspaces etc).

TorchRL is specifically oriented towards RL. Also, torchrl belongs to the pytorch ecosystem. As such it commits to the same philosophy as other libs (minimal dependency, sync/integration with latest torch releases and -- in the future -- concomitant release, etc)
In torchrl we work closely with the pytorch core team to deliver what we think is a generic RL library in pytorch (read: as least opinionated as possible), though in RL it's harder to stand up to that as in other libs IMO. This interaction leads us to escalate issues we observe in pytorch and push for changes that will make RL easier (eg. We talk regularly with people from distributed and functorch...).

Hope that helps, and that I did not say anything wrong about Salina 😄 
Perhaps @ludc would like to add something?

**Comment by ludc** [comment]
Hi, I think that the objectives are different. Salina is a lightweight library for sequential decision making (and RL in particular). It is very simple, and rely on few abstractions allowing to implement any algorithm (mono machine, multi CPUs, GPUs) in few lines. It is very research oriented with the idea of going as fast as possible from idea to implementation - it is the Swiss knive of RL and sequential decision making.  The TorchRL library - as far as I understand - is much specific to RL and has been conceived using classical RL concepts. Its objective is to become a reference RL library with benchmarked algorithms, distributed training, last pytorch functionalities etc.... It is a bigger library, easy to use, but more complicated if you want to implement crazy stuffs.  So I tend to think that it corresponds to two different needs: you have an idea, you want to test it quickly -> salina is a very good fit. You want to train large models, on complex environments in a distributed setting, use torchRL.  Vincent, does it also correspond to your point of view ?

**Comment by ludc** [comment]
But I agree that having on the two sides (Salina and TorchRL) a paragraph explaining the differences would be nice ! ( @vmoens )

**Comment by vmoens** [comment]
> The TorchRL library - as far as I understand - is much specific to RL and has been conceived using classical RL concepts.

Yes, indeed we explicitly want to stick to a terminology that is familiar to RL practitioners. It is important for us that users can navigate the repo easily and find the tools they need without effort.

> Its objective is to become a reference RL library with benchmarked algorithms, distributed training, last pytorch functionalities etc....

I would agree except for benchmarked algorithms: benchmarks are there only as examples for now. We don't really have the plan of having baselines implemented as such (unlike stable_baselines for instance).

> It is a bigger library, easy to use, but more complicated if you want to implement crazy stuffs.

I would leave that for the users to judge 😉, though I agree that some things may take "less lines of code" with Salina.

Also I should mention that we are (like Salina) very much research oriented. However, I would scope this a bit differently. In TorchRL, we'd like to provide most of the common primitives that exist in RL, e.g. computation of losses, returns etc. We'd like users to find these easily, even for things that are just a few lines of code long. I would guess that Salina is a bit more high-level on this point of view: from what I understand, there is no commitment to have primitives such as GAE or similar stuff.

**Comment by vmoens** [comment]
Closing this as this is not really an issue. Happy to move the discussion to the Discussions section if more needs to be clarified.
