### ISSUE TITLE
value of eps involving tanh in torchrl.modules.distributions

### ISSUE THREAD

**Issue by etaoxing** [facebookresearch/rl#71]
Is there a reason why 1e-4 is occasionally used as eps in these files over 1e-6? 

https://github.com/facebookresearch/rl/blob/e0f17e0a548310c2d6b009e5fc4a7bdbea18dd38/torchrl/modules/distributions/continuous.py#L77-L83

Docs for TanhDelta say: https://github.com/facebookresearch/rl/blob/e0f17e0a548310c2d6b009e5fc4a7bdbea18dd38/torchrl/modules/distributions/continuous.py#L459-L462
but specify:
https://github.com/facebookresearch/rl/blob/e0f17e0a548310c2d6b009e5fc4a7bdbea18dd38/torchrl/modules/distributions/continuous.py#L478-L479

In general 1e-6 is used such as in [rlkit](https://github.com/rail-berkeley/rlkit/blob/c81509d982b4d52a6239e7bfe7d2540e3d3cd986/rlkit/torch/distributions.py#L369), [garage](https://github.com/rlworkgroup/garage/blob/c56513f42be9cba2ef5426425a8ad36097e679c2/src/garage/torch/distributions/tanh_normal.py#L25), and [stable_baselines3](https://github.com/DLR-RM/stable-baselines3/blob/ed308a71be24036744b5ad4af61b083e4fbdf83c/stable_baselines3/common/distributions.py#L609).

**Comment by vmoens** [comment]
Excellent point.
We could also make it depend on the dtype by the way.

**Comment by vmoens** [comment]
Solved by #74

**Comment by etaoxing** [comment]
Looks good! 

> We could also make it depend on the dtype by the way.

Yes, I think stable_baselines3 does this for PPO. Most SAC implementations use 1e-6.
